# Generated by Django 4.1 on 2022-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, default='guest', max_length=32, null=True)),
                ('pregnancies', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('skin_thickness', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age', models.IntegerField()),
                ('outcome', models.IntegerField(default=9)),
            ],
        ),
    ]
