# Generated by Django 4.1.1 on 2023-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diabetes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="blood_pressure",
            field=models.IntegerField(verbose_name="Blood Pressure(Diastolic)"),
        ),
        migrations.AlterField(
            model_name="test",
            name="insulin",
            field=models.IntegerField(verbose_name="Insulin Level(U/ml)"),
        ),
        migrations.AlterField(
            model_name="test",
            name="skin_thickness",
            field=models.IntegerField(
                verbose_name="Skin Thickness(Tricep skinfold thickness(mm))"
            ),
        ),
    ]
